# Generated by Django 4.2.29 on 2026-04-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0003_streamvideo_show_in_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplaylist',
            name='is_coming_soon',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this playlist card as Coming Soon on Programs.'),
        ),
    ]
