# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_streaming", "0004_streamplaylist_is_coming_soon"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamvideo",
            name="player_layout",
            field=models.CharField(
                choices=[
                    ("auto", "Auto (from video)"),
                    ("landscape", "Landscape (16:9 frame)"),
                    ("portrait", "Portrait (9:16 frame)"),
                ],
                default="auto",
                help_text="Dashboard player frame. Auto uses pixel dimensions from transcoding and live playback metadata.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="streamvideo",
            name="source_height",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Source video height in pixels (filled when HLS processing completes).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="streamvideo",
            name="source_width",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Source video width in pixels (filled when HLS processing completes).",
                null=True,
            ),
        ),
    ]
