# Generated by Django 5.0.14 on 2026-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate_tracking', '0002_affiliateprofile_referral_base_and_sections'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleevent',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='saleevent',
            index=models.Index(fields=['referral', 'visitor_id'], name='affiliate_t_referra_dcdab6_idx'),
        ),
        migrations.AddIndex(
            model_name='saleevent',
            index=models.Index(fields=['referral', 'created_at'], name='affiliate_t_referra_00524b_idx'),
        ),
    ]
