# Generated by Django 5.0.14 on 2026-04-06 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('source_url', models.URLField(max_length=2048)),
                ('thumbnail', models.URLField(blank=True, max_length=2048)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(max_length=2048)),
                ('thumbnail', models.URLField(blank=True, max_length=2048)),
                ('duration', models.CharField(blank=True, help_text='Display e.g. "12:34" or "1:02:05"', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
