# Generated by Django 4.2.29 on 2026-04-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_article_keyword_dataset_auto_extract_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipGenerationState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('progression_by_category', models.JSONField(blank=True, default=dict)),
                ('recent_keyword_fingerprints', models.JSONField(blank=True, default=list)),
                ('recent_titles', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='generation_seed_category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='article',
            name='generation_seed_keyword',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='generation_seed_level',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.CreateModel(
            name='KeywordUsageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=32)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('keyword', models.CharField(blank=True, max_length=500)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_usage_stats', to='membership.articlekeyworddataset')),
            ],
            options={
                'indexes': [models.Index(fields=['dataset', 'last_used_at'], name='membership__dataset_634e9f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='keywordusagestat',
            constraint=models.UniqueConstraint(fields=('dataset', 'fingerprint'), name='membership_kwusage_dataset_fp'),
        ),
    ]
