# Generated by Django 4.2.29 on 2026-04-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_streaming', '0005_streamvideo_player_layout_and_source_dims'),
        ('membership', '0007_append_technological_evolution_paragraphs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStreamVideo',
            fields=[
            ],
            options={
                'verbose_name': 'Membership stream video',
                'verbose_name_plural': 'Membership stream videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('video_streaming.streamvideo',),
        ),
    ]
